"""empty message

Revision ID: 5b245184faed
Revises: 5be327c612ca
Create Date: 2024-07-12 16:13:39.886991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b245184faed'
down_revision = '5be327c612ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_Id_member_fkey', type_='foreignkey')
        batch_op.drop_column('Id_member')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Id_member', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_Id_member_fkey', 'member', ['Id_member'], ['Id_member'])

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
