"""empty message

Revision ID: 5be327c612ca
Revises: a8a1663b0d0d
Create Date: 2024-07-12 13:56:16.450689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be327c612ca'
down_revision = 'a8a1663b0d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscle_group',
    sa.Column('Id_musclegroup', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id_musclegroup'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('objective',
    sa.Column('Id_objective', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('Id_objective')
    )
    op.create_table('exercises',
    sa.Column('Id_exercise', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Link_video', sa.Integer(), nullable=True),
    sa.Column('Id_musclegroup', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Id_musclegroup'], ['muscle_group.Id_musclegroup'], ),
    sa.PrimaryKeyConstraint('Id_exercise'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('member',
    sa.Column('Id_member', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=60), nullable=False),
    sa.Column('Last_name', sa.String(length=60), nullable=False),
    sa.Column('Gender', sa.String(length=2), nullable=False),
    sa.Column('Height', sa.Float(), nullable=False),
    sa.Column('Weight', sa.Float(), nullable=False),
    sa.Column('Birthday', sa.String(length=10), nullable=False),
    sa.Column('City', sa.String(length=30), nullable=False),
    sa.Column('Country', sa.String(length=30), nullable=False),
    sa.Column('Id_objective', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Id_objective'], ['objective.Id_objective'], ),
    sa.PrimaryKeyConstraint('Id_member')
    )
    op.create_table('workout_plan',
    sa.Column('Id_workout', sa.Integer(), nullable=False),
    sa.Column('Sets', sa.String(length=50), nullable=False),
    sa.Column('Reps', sa.Integer(), nullable=False),
    sa.Column('Rest_time', sa.String(length=50), nullable=False),
    sa.Column('training_day', sa.Integer(), nullable=True),
    sa.Column('SuperSet', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('Id_member', sa.Integer(), nullable=True),
    sa.Column('Id_exercise', sa.Integer(), nullable=True),
    sa.Column('Id_musclegroup', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Id_exercise'], ['exercises.Id_exercise'], ),
    sa.ForeignKeyConstraint(['Id_member'], ['member.Id_member'], ),
    sa.ForeignKeyConstraint(['Id_musclegroup'], ['muscle_group.Id_musclegroup'], ),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('Id_workout')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Creation_date', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Id_member', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'member', ['Id_member'], ['Id_member'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Id_member')
        batch_op.drop_column('Creation_date')

    op.drop_table('workout_plan')
    op.drop_table('member')
    op.drop_table('exercises')
    op.drop_table('objective')
    op.drop_table('muscle_group')
    # ### end Alembic commands ###
