"""empty message

Revision ID: 6d6c76fe298f
Revises: a2bed1e572f4
Create Date: 2024-07-16 03:38:57.349848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6c76fe298f'
down_revision = 'a2bed1e572f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objective', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.String(length=60), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objective', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.drop_column('Name')

    # ### end Alembic commands ###
