"""empty message

Revision ID: a5ed878f4e4c
Revises: 
Create Date: 2024-07-16 03:17:36.270181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ed878f4e4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscle_group',
    sa.Column('Id_musclegroup', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id_musclegroup'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('objective',
    sa.Column('Id_objective', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('Id_objective')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('Creation_date', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('exercises',
    sa.Column('Id_exercise', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Link_video', sa.String(length=50), nullable=True),
    sa.Column('Id_musclegroup', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Id_musclegroup'], ['muscle_group.Id_musclegroup'], ),
    sa.PrimaryKeyConstraint('Id_exercise'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('member',
    sa.Column('Id_member', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=60), nullable=False),
    sa.Column('Last_name', sa.String(length=60), nullable=False),
    sa.Column('Gender', sa.String(length=2), nullable=False),
    sa.Column('Height', sa.Float(), nullable=False),
    sa.Column('Weight', sa.Float(), nullable=False),
    sa.Column('Birthday', sa.String(length=10), nullable=False),
    sa.Column('City', sa.String(length=30), nullable=False),
    sa.Column('Country', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('Id_objective', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Id_objective'], ['objective.Id_objective'], ),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('Id_member')
    )
    op.create_table('workout_plan',
    sa.Column('Id_workout', sa.Integer(), nullable=False),
    sa.Column('Sets', sa.String(length=50), nullable=False),
    sa.Column('Reps', sa.Integer(), nullable=False),
    sa.Column('Rest_time', sa.String(length=50), nullable=False),
    sa.Column('training_day', sa.Integer(), nullable=True),
    sa.Column('SuperSet', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('Id_member', sa.Integer(), nullable=True),
    sa.Column('Id_exercise', sa.Integer(), nullable=True),
    sa.Column('Id_musclegroup', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Id_exercise'], ['exercises.Id_exercise'], ),
    sa.ForeignKeyConstraint(['Id_member'], ['member.Id_member'], ),
    sa.ForeignKeyConstraint(['Id_musclegroup'], ['muscle_group.Id_musclegroup'], ),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('Id_workout')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_plan')
    op.drop_table('member')
    op.drop_table('exercises')
    op.drop_table('user')
    op.drop_table('objective')
    op.drop_table('muscle_group')
    # ### end Alembic commands ###
